name: Add-label
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved' && github.actor == 'elafelaf3'
    runs-on: ubuntu-latest
    steps:

      - name: Add-label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.html_url }} \
            --add-label approved
