name: Notify users based on PR labels
on:
  pull_request:
    types: [ labeled ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: install core
        run: |
         npm i @actions/github

      - name : install github
        run: |
          npm i @actions/core

      - name: Hello world action step
        id: hello
        uses: mahertaho/check-all-reviewers@v1.1
        with:
          who-to-greet: 'Mona the Octocat'
