name: Notify users based on PR labels
on:
  pull_request:
    types: [ labeled ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: mahertaho/check-all-reviewers@v1.2
        with:
          who-to-greet: 'Mona the Octocat'
