name: Notify users based on PR labels
on:
  pull_request:
      types: [ labeled ]
jobs:
  request:
    name: Request reviews on opened PRs
    runs-on: ubuntu-latest
    steps:
        - name: Create PR review request
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh pr edit ${{ github.event.pull_request.html_url }} \
                --add-reviewer hamzanael
