name: Assign a reviewer
on:
  pull_request:
      types: [ labeled ]
jobs:
  request:
    name: Request reviews on opened PRs
    runs-on: eg-default
    steps:
        - name: checkout repo
          uses: actions/checkout@v2
        - name: Create PR review request
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh pr edit ${{ github.event.pull_request.html_url }} \
                --add-reviewer maher
